source 'https://rubygems.org'

group :development, :test do
  gem 'codecov', :require => false
  gem 'rake'
  gem 'rubocop', '~> 0.72.0', :require => false
  gem 'simplecov', :require => false
  gem 'test-unit'
  gem 'yard'
end
